namespace RC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class posts : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Posts  (Content, Date, organizationId) VALUES ('The chair of our board of directors James Weddle, and our president, Robert Cannon, recently honored the resting place of Robert Barnes at Bellefontaine Cemetery and Arboretum.Founder of Barnes Hospital, Barnes requested that he be remembered in this simple way.','02 / 04 / 2019 12:25:37 AM',5)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Locker cleanout in the lower school...the aftermath. Thank you to the students who helped clean up after the cleanout!','02/04/2019 12:25:37 AM',143)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The AMSA JCL kicked off finals week with some positivity for the students. On the glass at the Upper School Office are friendship bracelets attached to latin quotes that the club has been working on for more than a month now.Each day there will be more bracelets put up for students to take! The JCL hopes to see students wearing them as they finish up the last week at AMSA.','02/04/2019 12:25:37 AM',143)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('On Tuesday we said hello to next year’s 6th graders (plus a few 7th graders). They got to know each other over pizza and games joined by current 6th graders and staff.We look forward to seeing them back on Aug. 26! Tomorrow night we say goodbye to our graduating seniors many of whom were similar nervous newcomers to AMSA just a few short years ago','03/04/2019 12:25:37 AM',143)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A few more images from the senior trip to Disney!','04/04/2019 12:25:37 AM',143)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA students are known for being innovative. These 7th graders invented invisible benches to rest on between classes.','05/04/2019 12:25:37 AM',144)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('It’s safe to say everyone had a good time on the 7th grade class trip to Canobie Lake Park today!','06/04/2019 12:25:37 AM',144)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Varsity Softball seniors Erin Dean (#5) and Ella Kinney (#10) were honored prior to yesterdays game against visiting Douglas. Piper Kinney went 2-for-3 with two RBIs while Dean pitched a complete game and added two hits to lift the Eagles over the Tigers 4-1','07/04/2019 12:25:37 AM',144)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA’s newest Eagle Award recipients are 8th grader Wesley Souza and 7th grader Dylan Nash. Each was nominated by a teacher for displaying behavior that exemplifies AMSA’s culture of respect – for oneself, for others and for the community. Congratulations Wesley and Dylan for earning those pins!','08/04/2019 12:25:37 AM',144)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Black Student Unions end-of-year send-off was last week. Best of luck to the seniors moving on from the club and AMSA!','09/04/2019 12:25:37 AM',144)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Yesterday, AMSA’s Black Student Union (BSU) hosted lower school students for an afternoon of games Kahoot, and delicious free food! It was an opportunity for younger students to get to know high schoolers and ask questions about the club and the upper school in general.','10/04/2019 12:25:37 AM',145)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Has spring finally sprung? One sure sign is teachers finally able to take some classes outside. Here is Mr.Brandes conducting a lesson yesterday at the picnic tables.','11/04/2019 12:25:37 AM',145)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('ATTENTION ALL MIDDLE SCHOOLERS! We are inviting all students from 6th through 8th grade for an afternoon of games Kahoot, and delicious free food!! Join us this Thursday, May 16th from 3:30-4:30 in Mr.Anderson’s room (200) for an afternoon of fun where you will also get to meet and interact with high schoolers and ask us any questions you may have! Hope to see you there!!','12/04/2019 12:25:37 AM',145)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bring your sweet tooth to the Spring Fling Bake Thing on Friday, May 10! The Best Buddies club will be selling baked items during all three lunches in the upper and lower school cafeterias. Proceeds benefit the club’s volunteer activities.','09 /04/2019 12:25:37 AM',145)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('More Spirit Week Characters... or a Duo..or perhaps both!','04 /04/2019 12:25:37 AM',145)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Meanwhile, there was a buzz in the upper school as students received their schedules for next year.','01/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Locker cleanout in the lower school...the aftermath. Thank you to the students who helped clean up after the cleanout!','02/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The AMSA JCL kicked off finals week with some positivity for the students. On the glass at the Upper School Office are friendship bracelets attached to latin quotes that the club has been working on for more than a month now.Each day there will be more bracelets put up for students to take! The JCL hopes to see students wearing them as they finish up the last week at AMSA.','02/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('On Tuesday we said hello to next year’s 6th graders (plus a few 7th graders). They got to know each other over pizza and games joined by current 6th graders and staff.We look forward to seeing them back on Aug. 26! Tomorrow night we say goodbye to our graduating seniors many of whom were similar nervous newcomers to AMSA just a few short years ago','03/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A few more images from the senior trip to Disney!','04/04/2019 12:25:37 AM',146)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA students are known for being innovative. These 7th graders invented invisible benches to rest on between classes.','05/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('It’s safe to say everyone had a good time on the 7th grade class trip to Canobie Lake Park today!','06/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Varsity Softball seniors Erin Dean (#5) and Ella Kinney (#10) were honored prior to yesterdays game against visiting Douglas. Piper Kinney went 2-for-3 with two RBIs while Dean pitched a complete game and added two hits to lift the Eagles over the Tigers 4-1','07/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA’s newest Eagle Award recipients are 8th grader Wesley Souza and 7th grader Dylan Nash. Each was nominated by a teacher for displaying behavior that exemplifies AMSA’s culture of respect – for oneself, for others and for the community. Congratulations Wesley and Dylan for earning those pins!','08/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Black Student Unions end-of-year send-off was last week. Best of luck to the seniors moving on from the club and AMSA!','09/04/2019 12:25:37 AM',147)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Yesterday, AMSA’s Black Student Union (BSU) hosted lower school students for an afternoon of games Kahoot, and delicious free food! It was an opportunity for younger students to get to know high schoolers and ask questions about the club and the upper school in general.','10/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Has spring finally sprung? One sure sign is teachers finally able to take some classes outside. Here is Mr.Brandes conducting a lesson yesterday at the picnic tables.','11/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('ATTENTION ALL MIDDLE SCHOOLERS! We are inviting all students from 6th through 8th grade for an afternoon of games Kahoot, and delicious free food!! Join us this Thursday, May 16th from 3:30-4:30 in Mr.Anderson’s room (200) for an afternoon of fun where you will also get to meet and interact with high schoolers and ask us any questions you may have! Hope to see you there!!','12/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bring your sweet tooth to the Spring Fling Bake Thing on Friday, May 10! The Best Buddies club will be selling baked items during all three lunches in the upper and lower school cafeterias. Proceeds benefit the club’s volunteer activities.','09 /04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('More Spirit Week Characters... or a Duo..or perhaps both!','04 /04/2019 12:25:37 AM',148)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Meanwhile, there was a buzz in the upper school as students received their schedules for next year.','01/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Locker cleanout in the lower school...the aftermath. Thank you to the students who helped clean up after the cleanout!','02/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The AMSA JCL kicked off finals week with some positivity for the students. On the glass at the Upper School Office are friendship bracelets attached to latin quotes that the club has been working on for more than a month now.Each day there will be more bracelets put up for students to take! The JCL hopes to see students wearing them as they finish up the last week at AMSA.','02/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('On Tuesday we said hello to next year’s 6th graders (plus a few 7th graders). They got to know each other over pizza and games joined by current 6th graders and staff.We look forward to seeing them back on Aug. 26! Tomorrow night we say goodbye to our graduating seniors many of whom were similar nervous newcomers to AMSA just a few short years ago','03/04/2019 12:25:37 AM',146)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A few more images from the senior trip to Disney!','04/04/2019 12:25:37 AM',146)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA students are known for being innovative. These 7th graders invented invisible benches to rest on between classes.','05/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('It’s safe to say everyone had a good time on the 7th grade class trip to Canobie Lake Park today!','06/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Varsity Softball seniors Erin Dean (#5) and Ella Kinney (#10) were honored prior to yesterdays game against visiting Douglas. Piper Kinney went 2-for-3 with two RBIs while Dean pitched a complete game and added two hits to lift the Eagles over the Tigers 4-1','07/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA’s newest Eagle Award recipients are 8th grader Wesley Souza and 7th grader Dylan Nash. Each was nominated by a teacher for displaying behavior that exemplifies AMSA’s culture of respect – for oneself, for others and for the community. Congratulations Wesley and Dylan for earning those pins!','08/04/2019 12:25:37 AM',147)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('AMSA Black Student Unions end-of-year send-off was last week. Best of luck to the seniors moving on from the club and AMSA!','09/04/2019 12:25:37 AM',147)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Yesterday, AMSA’s Black Student Union (BSU) hosted lower school students for an afternoon of games Kahoot, and delicious free food! It was an opportunity for younger students to get to know high schoolers and ask questions about the club and the upper school in general.','10/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Has spring finally sprung? One sure sign is teachers finally able to take some classes outside. Here is Mr.Brandes conducting a lesson yesterday at the picnic tables.','11/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('ATTENTION ALL MIDDLE SCHOOLERS! We are inviting all students from 6th through 8th grade for an afternoon of games Kahoot, and delicious free food!! Join us this Thursday, May 16th from 3:30-4:30 in Mr.Anderson’s room (200) for an afternoon of fun where you will also get to meet and interact with high schoolers and ask us any questions you may have! Hope to see you there!!','12/04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bring your sweet tooth to the Spring Fling Bake Thing on Friday, May 10! The Best Buddies club will be selling baked items during all three lunches in the upper and lower school cafeterias. Proceeds benefit the club’s volunteer activities.','09 /04/2019 12:25:37 AM',148)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('More Spirit Week Characters... or a Duo..or perhaps both!','04 /04/2019 12:25:37 AM',148)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Congratulations Class of 2019! This week, 1,086 undergraduates and 1,905 graduate students received their MIT diplomas. Please tag yourself in the photos if you see yourself!','06/04/2019 12:25:37 AM',190)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('This week, 1,086 undergraduates and 1,905 graduate students receive their MIT diplomas','08/04/2019 12:25:37 AM',190)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('These images were captured at the 2019 Investiture of Doctoral Hoods and Degree Conferral.','10/04/2019 12:25:37 AM',190)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Investiture of Doctoral Hoods starts in one hour.','09 /05/2019 12:25:37 AM',190)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('With a 4-0 victory over Georgia, Stanford Womens Tennis gained its 20th NCAA crown on Sunday night.','11 /05/2019 12:25:37 AM',190)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('What used to be called Serra House, in Stern Hall, has been renamed in honor of alumna Sally Ride, and last week residents had a chance to celebrate with a special guest (can you spot her?): the barrier-breaking astronauts mother, Joyce. The dedication speaks to the world what we want these walls to hold, resident fellow Michelle Reininger said. We want them to hold all members of our community; we want them to hold hope and inspiration, tenacity and a desire to make our world a better place.', '01 /05/2019 12:25:37 AM',191)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Today marks 38 years since Stanford surgeon Bruce Reitz and team performed the world’s first successful heart-lung transplant. The operation came just in time to save Mary Gohlke, a newspaper executive dying from pulmonary hypertension. “The appearance of[her] totally empty chest was indeed a dramatic moment,” Reitz later recalled. “I wondered, ‘Is this really going to work out?’” Gohlke went on to live for five more years and wrote a book, “I’ll Take Tomorrow,” about her role in the pioneering medical moment. Stanford Hospital has since performed the operation on more than 200 additional patients two of whom lived more than 26 years after their surgeries.','02 /05/2019 12:25:37 AM',191)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Morning Exercises procession','03 /05/2019 12:25:37 AM',191)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('At commencement, students from Harvard’s various Schools carry props that in some way speak to the broader mission of the School. Graduates wave their props during the School’s introduction in the ceremony.','07/05/2019 12:25:37 AM',191)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('On Memorial Day, we honor the military women and men who have served and are presently serving.','09/05/2019 12:25:37 AM',191)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Ninth graders from Seattle recently visited Harvard and MIT.The students toured both campuses learned about admissions and financial aid, sat in on classes and met with first-generation students.','11/05/2019 12:25:37 AM',192)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('1,127 Caltech alumni, parents faculty, staff, students and friends from 44 states and 16 countries donated nearly $225,000 on Caltech Giving Day to help propel Caltech forward! Thank you!','01/06/2019 12:25:37 AM',192)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Happy National Turtle Day! As of last count, Throop Pond is home to 98 red-eared sliders - youre bound to meet many of the ponds reptilian residents as they bask in the sun on rocks ringing the waters edge.','02/06/2019 12:25:37 AM',192)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Four teams entered the WABOBABOT Competition, but only one could come out on top…Congratulations to Team Misteltein for taking home the top prize in the 34th Annual Engineering Design Competition, which is the capstone of the ME 72 course! Flip through the photos to get a sense of the excitement!','03/06/2019 12:25:37 AM',192)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A team of Seychellois and University of Oxford volunteers including researchers scientists and Queens College students have cleared 50,000 flip-flops from the Aldabra Atol','04/06/2019 12:25:37 AM',192)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Former student Matt Pierri is co-founder and CEO of the SociAbility app - a crowd-sourced mobile platform empowering greater social inclusion for people with access needs','05/06/2019 12:25:37 AM',193)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('10 ventures from the Oxford Foundrys high-growth Accelerator programme, OXFO L.E.V8, pitched to an audience of high-profile guests from the world of venture capital. Special guests included Biz Stone, co-founder of Twitter, Jelly and Medium, and Arlan Hamilton, founder and Managing Partner at US-based venture firm Backstage Capital.','06/06/2019 12:25:37 AM',193)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Every summer swifts return to the UK after their long migration from Africa, and for years the Museum of Natural History tower has been a favourite nesting site','07/06/2019 12:25:37 AM',193)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('You are currently listening to the library','08/06/2019 12:25:37 AM',193)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Its been autumnal here in Cambridge, bring back summer! More of this please!','09/06/2019 12:25:37 AM',193)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Gate of Honour at Gonville & Caius College, Cambridge is passed through by graduating students on their way to receive their degrees','10/06/2019 12:25:37 AM',194)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('In Cambridge? Hear primatologist and conservationist Dr Jane Goodall DBE, speak on Reasons for Hope at 5.30pm on Tuesday 18 June, at the Lady Mitchell Hall','10/06/2019 03:25:37 AM',194)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bronze Horse at Jesus College','11/06/2019 12:25:37 AM',194)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('While you are revising, make sure you do something physical. Like going for a walk! Better yet, a photo walk.This picture by Daria, an LLM student at Gonville & Caius College, Cambridge, was taken on one','12/06/2019 12:25:37 AM',194)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Congratulations to everyone graduating today.','09 /06/2019 12:25:37 AM',194)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bridge of Sighs - St John’s College','04 /06/2019 12:25:37 AM',195)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('70 years ago this week, EDSAC, the worlds first stored-program digital computer, ran its first successful program.','11 /06/2019 12:25:37 AM',195)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Gonville & Caius College is one of the oldest and largest colleges of the University of Cambridge. Founded in 1348, the College combines the best of Cambridge tradition with 21st century teaching and research.','11 /06/2019 05:25:37 AM',195)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('so we say farewell to our Target Oxbridge students who leave Cambridge today after 3 days exploring the University and the city.We hope to welcome many of you here again next year…keep up the hard work!','11 /06/2019 07:25:37 AM',195)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Congratulations Class of 2019! This week, 1,086 undergraduates and 1,905 graduate students received their MIT diplomas. Please tag yourself in the photos if you see yourself!','06/04/2019 12:25:37 AM',196)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('This week, 1,086 undergraduates and 1,905 graduate students receive their MIT diplomas','08/04/2019 12:25:37 AM',196)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('These images were captured at the 2019 Investiture of Doctoral Hoods and Degree Conferral.','10/04/2019 12:25:37 AM',196)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Investiture of Doctoral Hoods starts in one hour.','09 /05/2019 12:25:37 AM',196)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('With a 4-0 victory over Georgia, Stanford Womens Tennis gained its 20th NCAA crown on Sunday night.','11 /05/2019 12:25:37 AM',196)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('What used to be called Serra House, in Stern Hall, has been renamed in honor of alumna Sally Ride, and last week residents had a chance to celebrate with a special guest (can you spot her?): the barrier-breaking astronauts mother, Joyce. The dedication speaks to the world what we want these walls to hold, resident fellow Michelle Reininger said. We want them to hold all members of our community; we want them to hold hope and inspiration, tenacity and a desire to make our world a better place.', '01 /05/2019 12:25:37 AM',197)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Today marks 38 years since Stanford surgeon Bruce Reitz and team performed the world’s first successful heart-lung transplant. The operation came just in time to save Mary Gohlke, a newspaper executive dying from pulmonary hypertension. “The appearance of[her] totally empty chest was indeed a dramatic moment,” Reitz later recalled. “I wondered, ‘Is this really going to work out?’” Gohlke went on to live for five more years and wrote a book, “I’ll Take Tomorrow,” about her role in the pioneering medical moment. Stanford Hospital has since performed the operation on more than 200 additional patients two of whom lived more than 26 years after their surgeries.','02 /05/2019 12:25:37 AM',197)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Morning Exercises procession','03 /05/2019 12:25:37 AM',197)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('At commencement, students from Harvard’s various Schools carry props that in some way speak to the broader mission of the School. Graduates wave their props during the School’s introduction in the ceremony.','07/05/2019 12:25:37 AM',197)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('On Memorial Day, we honor the military women and men who have served and are presently serving.','09/05/2019 12:25:37 AM',197)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Ninth graders from Seattle recently visited Harvard and MIT.The students toured both campuses learned about admissions and financial aid, sat in on classes and met with first-generation students.','11/05/2019 12:25:37 AM',198)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('1,127 Caltech alumni, parents faculty, staff, students and friends from 44 states and 16 countries donated nearly $225,000 on Caltech Giving Day to help propel Caltech forward! Thank you!','01/06/2019 12:25:37 AM',198)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Happy National Turtle Day! As of last count, Throop Pond is home to 98 red-eared sliders - youre bound to meet many of the ponds reptilian residents as they bask in the sun on rocks ringing the waters edge.','02/06/2019 12:25:37 AM',198)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Four teams entered the WABOBABOT Competition, but only one could come out on top…Congratulations to Team Misteltein for taking home the top prize in the 34th Annual Engineering Design Competition, which is the capstone of the ME 72 course! Flip through the photos to get a sense of the excitement!','03/06/2019 12:25:37 AM',198)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A team of Seychellois and University of Oxford volunteers including researchers scientists and Queens College students have cleared 50,000 flip-flops from the Aldabra Atol','04/06/2019 12:25:37 AM',198)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Former student Matt Pierri is co-founder and CEO of the SociAbility app - a crowd-sourced mobile platform empowering greater social inclusion for people with access needs','05/06/2019 12:25:37 AM',199)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('10 ventures from the Oxford Foundrys high-growth Accelerator programme, OXFO L.E.V8, pitched to an audience of high-profile guests from the world of venture capital. Special guests included Biz Stone, co-founder of Twitter, Jelly and Medium, and Arlan Hamilton, founder and Managing Partner at US-based venture firm Backstage Capital.','06/06/2019 12:25:37 AM',199)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Every summer swifts return to the UK after their long migration from Africa, and for years the Museum of Natural History tower has been a favourite nesting site','07/06/2019 12:25:37 AM',199)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('You are currently listening to the library','08/06/2019 12:25:37 AM',199)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Its been autumnal here in Cambridge, bring back summer! More of this please!','09/06/2019 12:25:37 AM',199)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('The Gate of Honour at Gonville & Caius College, Cambridge is passed through by graduating students on their way to receive their degrees','10/06/2019 12:25:37 AM',200)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('In Cambridge? Hear primatologist and conservationist Dr Jane Goodall DBE, speak on Reasons for Hope at 5.30pm on Tuesday 18 June, at the Lady Mitchell Hall','10/06/2019 03:25:37 AM',200)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bronze Horse at Jesus College','11/06/2019 12:25:37 AM',200)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('While you are revising, make sure you do something physical. Like going for a walk! Better yet, a photo walk.This picture by Daria, an LLM student at Gonville & Caius College, Cambridge, was taken on one','12/06/2019 12:25:37 AM',200)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Congratulations to everyone graduating today.','09 /06/2019 12:25:37 AM',200)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bridge of Sighs - St John’s College','04 /06/2019 12:25:37 AM',201)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('70 years ago this week, EDSAC, the worlds first stored-program digital computer, ran its first successful program.','11 /06/2019 12:25:37 AM',201)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Gonville & Caius College is one of the oldest and largest colleges of the University of Cambridge. Founded in 1348, the College combines the best of Cambridge tradition with 21st century teaching and research.','11 /06/2019 05:25:37 AM',201)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('so we say farewell to our Target Oxbridge students who leave Cambridge today after 3 days exploring the University and the city.We hope to welcome many of you here again next year…keep up the hard work!','11 /06/2019 07:25:37 AM',201)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Just polishing up the SILVAware','01/05/2019 12:25:37 AM',256)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Bernardo Silva - Professional Trophy Lifter','02/05/2019 12:25:37 AM',256)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('International duty calls','03/05/2019 12:25:37 AM',256)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('some incredible shots from our incredible season!','04/05/2019 12:25:37 AM',256)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Emirates Stadium will look incredible in eFootball PES 2020! Coming September 10','05/05/2019 12:25:37 AM',260)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Our club flag will remain at half-mast at Arsenal Training Centre.In loving memory of Jose Antonio Reyes','06/05/2019 12:25:37 AM',260)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('A true Blue.','07/05/2019 12:25:37 AM',263)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Nothing but the best for the future, Captain!','08/05/2019 12:25:37 AM',263)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Eid Mubarak to all the Blues celebrating around the world! We wish you a very happy Eid al-Fitr!','09/05/2019 12:25:37 AM',263)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Walcott and Tosun on target as we sign off for the season. Well played today, Blues.','10/05/2019 12:25:37 AM',263)");

            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Newcastle Uniteds fixtures for the 2010 /20 Premier League season will be announced in half an hour!','11/05/2019 12:25:37 AM',268)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('Paul Dummett says he and the rest of the Newcastle United players are looking forward to seeing the fixture list for the 2010 /20 Premier League season, which will be announced on nufc.co.uk tomorrow at 9am (BST).','12/05/2019 12:25:37 AM',268)");
            Sql("INSERT INTO Posts (Content, Date, organizationId) VALUES ('DBRAVKA HELPS SLOVAKIA RECORD EMPHATIC WIN Martin D?bravka helped Slovakia to a second 5-1 victory in succession on Tuesday as they thrashed Azerbaijan in their European Championship qualifier','09 /05/2019 12:25:37 AM',268)");

        }

        public override void Down()
        {
        }
    }
}
