// <auto-generated />
namespace RC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201906132019108_populate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
